---
- hosts: mikrotiks
  connection: network_cli
  gather_facts: no

  tasks: 
  - name: añadir una IP a una lista blanca en todos los equipos
    raw: /ip firewall address-list add list=Whitelist address=91.247.176.2

...
