---
- hosts: mikrotiks
  connection: network_cli
  gather_facts: no

  tasks:
  - name: Establecer DNS servidor primario y secundario al router
    raw: /ip dns set servers=8.8.8.8,1.1.1.1 allow-remote-requests=yes

...
